
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label3;

	private global::Gtk.Entry entryIP;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entryUserName;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label labelPassword;

	private global::Gtk.Entry entryPassword;

	private global::Gtk.Button buttonConnect;

	private global::Gtk.HButtonBox hbuttonbox3;

	private global::Gtk.VBox vbox7;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView chatTextView;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Entry entryMessage;

	private global::Gtk.Button buttonSend;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("CrypteChat");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Server IP/Hostname:");
		this.hbox9.Add(this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entryIP = new global::Gtk.Entry();
		this.entryIP.CanFocus = true;
		this.entryIP.Name = "entryIP";
		this.entryIP.Text = global::Mono.Unix.Catalog.GetString("127.0.0.1");
		this.entryIP.IsEditable = true;
		this.entryIP.InvisibleChar = '●';
		this.hbox9.Add(this.entryIP);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entryIP]));
		w2.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Username:");
		this.hbox9.Add(this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label1]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entryUserName = new global::Gtk.Entry();
		this.entryUserName.CanFocus = true;
		this.entryUserName.Name = "entryUserName";
		this.entryUserName.IsEditable = true;
		this.entryUserName.InvisibleChar = '●';
		this.hbox9.Add(this.entryUserName);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entryUserName]));
		w4.Position = 3;
		this.hbox3.Add(this.hbox9);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox9]));
		w5.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.labelPassword = new global::Gtk.Label();
		this.labelPassword.Name = "labelPassword";
		this.labelPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
		this.hbox5.Add(this.labelPassword);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.labelPassword]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entryPassword = new global::Gtk.Entry();
		this.entryPassword.CanFocus = true;
		this.entryPassword.Name = "entryPassword";
		this.entryPassword.IsEditable = true;
		this.entryPassword.Visibility = false;
		this.entryPassword.InvisibleChar = '●';
		this.hbox5.Add(this.entryPassword);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryPassword]));
		w7.Position = 1;
		this.hbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox5]));
		w8.Position = 1;
		this.hbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox3]));
		w9.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonConnect = new global::Gtk.Button();
		this.buttonConnect.CanFocus = true;
		this.buttonConnect.Name = "buttonConnect";
		this.buttonConnect.UseUnderline = true;
		this.buttonConnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.hbox1.Add(this.buttonConnect);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonConnect]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox();
		this.hbuttonbox3.Name = "hbuttonbox3";
		this.vbox1.Add(this.hbuttonbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox3]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.chatTextView = new global::Gtk.TextView();
		this.chatTextView.CanFocus = true;
		this.chatTextView.Name = "chatTextView";
		this.chatTextView.Editable = false;
		this.chatTextView.CursorVisible = false;
		this.chatTextView.WrapMode = ((global::Gtk.WrapMode)(3));
		this.chatTextView.LeftMargin = 2;
		this.GtkScrolledWindow.Add(this.chatTextView);
		this.vbox7.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow]));
		w14.Position = 0;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entryMessage = new global::Gtk.Entry();
		this.entryMessage.CanFocus = true;
		this.entryMessage.Name = "entryMessage";
		this.entryMessage.IsEditable = true;
		this.entryMessage.InvisibleChar = '●';
		this.hbox7.Add(this.entryMessage);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entryMessage]));
		w15.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonSend = new global::Gtk.Button();
		this.buttonSend.CanFocus = true;
		this.buttonSend.Name = "buttonSend";
		this.buttonSend.UseUnderline = true;
		this.buttonSend.Label = global::Mono.Unix.Catalog.GetString("Send");
		this.hbox7.Add(this.buttonSend);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonSend]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox7.Add(this.hbox7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox1.Add(this.vbox7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox7]));
		w18.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 867;
		this.DefaultHeight = 400;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonConnect.Clicked += new global::System.EventHandler(this.buttonConnect_Click);
		this.entryMessage.Activated += new global::System.EventHandler(this.messageEnter);
		this.buttonSend.Clicked += new global::System.EventHandler(this.buttonSend_Click);
	}
}
